import { proxyApi } from '../../../lib/api-proxy';
export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';
export const GET = proxyApi;
export const POST = proxyApi;
export const DELETE = proxyApi;
export const PUT = proxyApi;
export const PATCH = proxyApi;
export const OPTIONS = proxyApi;
export const HEAD = proxyApi;
